### ISSUE TITLE
ExceptionHandler is incompatible with Laravel 7+

### ISSUE THREAD

**Issue by filakhtov** [ratehub/laravel-newrelic#10]
Hello guys 👋!

I have just discovered a compatibility problem between this library and Laravel 7+, basically:
```
Declaration of RateHub\NewRelic\Exceptions\ExceptionHandler::report(Exception $e) must be compatible with Illuminate\Contracts\Debug\ExceptionHandler::report(Throwable $e)
```
due to Laravel changing their type hints from `Exception` to `Throwable` on all the interface methods. Wondering how we want to proceed with fixing this?

So far, my immediate thoughts are:
- Maintain two separate exception handlers and register based on the actual framework version
- Drop support for older framework versions (bad idea IMO, because Laravel 6 is LTS)

Looking forward for any feedback and suggestions.

**Comment by filakhtov** [comment]
Hey @Voziv, can we please get your eyes on this issue and a proposed solution in the #9 so we can get things moving? Thanks in advance 🙇‍♂️

**Comment by Voziv** [comment]
Closing as I think this is fixed now
